import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header'
import styles from '../styles/Home.module.css'
import styled from '@emotion/styled'

const HomeContainer = styled.div`
width: 100%;
height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  `

export default function Home() {
  return (
    <HomeContainer className={styles.container}>
      <Head>
        <title>Portifólio Igo Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/gr.png" />
      </Head>
      <Header/>
    </HomeContainer>
  )
}
